### PR TITLE
Added the option to ignore variables based on a prefix

### PR DESCRIPTION
**Pull request by roryhardy**
I found that I needed to be able to omit certain variables from my JSON file and the simplest way to do that was to namespace them.  I was thinking this might be useful to someone else as well so I figured I'd contribute back.

Please let me know if there's anything else I need to do.

### CODE REVIEW

**Comment by bjankord** [comment]
+1, this would be a really nice addition

**Comment by ixrock** [comment]
Ok, but before I merge PR please rework it a bit:
1) Rename `ignorePrefix` to `ignoreWithPrefix` cause it misleads that in the result I get a variable with removed prefix (`_someThing => someThing`)
2) Don't use regular expression to check such simple thing:

``` javascript
var prefix = options.ignoreWithPrefix || '';
var name = rule.name.substr(1); // remove "@"
var value = rule.value.value[0]; // can be less.tree.Color, less.tree.Expression, etc.
if(!prefix || prefix && value.substr(0, prefix.length) !== prefix) lessVars[name] = value.toCSS();
```

**Comment by roryhardy** [comment]
@ixrock, the updates have been made.

**Comment by roryhardy** [comment]
@ixrock any chance we could get this change-set pushed to NPM? Is there anything I can do to help with that?  Thanks!

**Pull request merged**
